In [22]:
import tensorflow as tf
print("Tensorflow: v" + tf.__version__)

Tensorflow: v2.4.1


##  Tensors
- Each tensors has a data type and shape
- Mostly will be using numbers but there are strings and other too
- Shape = representation of the tensor 
- `tf.Variable(value, datatype)`
- Scalar = 0 degree (rank), but there are other tensors with higher degrees/rank such as matrix/vectors where there are more dimensions

In [21]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(3.1415, tf.float64)
rank1_tensors = tf.Variable(["Hello", "Bob"], tf.string)
rank2_tensors = tf.Variable([["John", "Bob", "Frank"], ["Joe", "Helen", "Julie"]], tf.string) #matrix

You can use `tf.rank` to determine what rank the Tensor is

In [39]:
tf.rank(string)
tf.rank(rank1_tensors)
tf.rank(rank2_tensors)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

`.shape` - how many elements in each list [length of list, how many in each list]

In [23]:
rank2_tensors.shape

TensorShape([2, 3])

## Reshape Tensor
- You can also change the shape of the tensors
- eg. You can change a rank 2 tensor into a rank 1
- `tf.ones()` make a list of ones
- `tf.reshape(tensor, shape)` to reshape the tensor

In [37]:
tensor1 = tf.ones([1,2,3]) 
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshape exsisting tensor to a new shape
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 infer what the number need to be, it will calculate it for us

However, the number of element in the reshape should be the same as the original

In [38]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of Tensors
- Variables 
- Constant 
- Placeholder 
- SpareTensor

All types of tensors except for Variable are immutable (can't change)

## Evaluating Tensors
```
with tf.Session() as sess: #create a session using default graph
    tensor.eval()
```

- `tensor_name.eval()` to evaluate after creating a session

## Examples with Reshaping Tensor

In [49]:
# tf.zeros and tf.ones are pretty much the same except for 0 and 1
t = tf.zeros([5,5,5,5])
print(t)

# reshape to a flat shape (scalar??)
t = tf.reshape(t, [625])
print(t)

t = tf.reshape(t, [125, -1])
print(t)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0.